### ISSUE TITLE
Impossible to use string values in methods

### ISSUE THREAD

**Issue by Zasco** [rewieer/TaskSchedulerBundle#4] opened 2019-02-11 22:54 UTC
Using the `minutes()` and `hours()` methods of class `Rewieer\TaskSchedulerBundle\Task\Schedule`, it is impossible to use a *string* as value. Their declaration requires it to be an *int* and thus prevents the use of the wrapper for such cases.

Current workaround is to use `Cron\CronExpression`'s `setPart()`.

**Comment by rewieer** [comment] 2019-02-12 13:58
Can you explain what kind of values are you trying to feed these methods ?

**Comment by Zasco** [comment] 2019-02-15 22:45
For instance, it is impossible to use `minutes('1,2,3,5,8,13,21,34,55')`.

Moreover, I found that using an *int* **0** will be displayed likewise in `getExpression()`, but will act as an __*__ while this is not the case when using *string* **0**.
**However**, this rather seems to be a `Cron/CronExpression` problem as it happens even when bypassing the wrappers that anyway pass the values as is and setting the `Cron` directly;

**Comment by rewieer** [comment] 2019-02-19 08:17
For the `minutes` function indeed I didn't plan to use it with different precise minutes, so this is a use case to add.

So when using `'0'` it works as intended but `0` is replaced by * ? Is it really the getter fault, or did you use a setter function that assumes that 0 = * and therefore stored at it as * ?
I'm not much into CRON jobs these days so I don't have much time to investigate this more

**Comment by Zasco** [comment] 2019-02-22 00:10
I didn't investigate much more either, just enough to find it must be a `Cron/CronExpression` problem as no custom code was used here, only `CronExpression->setPart()`. I will submit them and link the thread to this one.
Here is the trace :

* Create a new task extending `AbstractScheduledTask` and register it in the scheduler;
    * In the initialize method, call `$schedule->getCron()->setPart(CronExpression::minutes, 0)`;
        * $schedule->getCron()->getExpression() will now return __0 * * * *__
        * Call recurrency : * * * * *

    **OR**

    * In the initialize method, call `$schedule->getCron()->setPart(CronExpression::minutes, '0')`;
        * `$schedule->getCron()->getExpression()` will now return __0 * * * *__
        * Call recurrency : 0 * * * *

For the use case, I already made a commit for it on my fork. However I don't know if the tests should be updated accordingly.


**Packages versions :**
dragonmantank/cron-expression : v2.2.0
symfony/symfony : v2.8.49
rewieer/taskschedulerbundle : 0.1.0

**Comment by rewieer** [comment] 2019-02-26 15:58
Indeed this seems to be directly related to the Cron library. We should wait to see if this is going to be fixed.
If unfortunately, it wont, we shall fix it ourselves.

**Comment by marcin-derlukiewicz** [comment] 2021-02-03 14:36
is this still relevant?

**Comment by rewieer** [comment] 2021-02-03 16:16
@marcin-derlukiewicz It might be. Can you propose a PR ?

**Comment by marcin-derlukiewicz** [comment] 2021-02-07 11:45
@Zasco you mentioned that you made some kind of fix can you link it?

**Comment by NicoHaase** [comment] 2021-02-08 15:59
@marcin-derlukiewicz I would assume that https://github.com/Zasco/TaskSchedulerBundle/commit/8aba436d9804a4a740b14212884d6b36a8c9141e is the commit you are looking for?

**Comment by marcin-derlukiewicz** [comment] 2021-02-08 21:23
ok, so for this functionality there are 2 methods already:

you can use shrothand method $schedule->setPart() (without getCron()) like here https://github.com/rewieer/TaskSchedulerBundle/blob/eb6a27226b6dba8beb1febe88197b68f6830f6ba/Tests/Task/ScheduleTest.php#L97

or use setExpression for entire definition like this:

https://github.com/rewieer/TaskSchedulerBundle/blob/eb6a27226b6dba8beb1febe88197b68f6830f6ba/Tests/Task/ScheduleTest.php#L85

**Comment by fwolfsjaeger** [comment] 2021-07-23 15:19
Sorry, I just noticed that there already is a fix for this. Just decline my PR if you want to go with the solution from @Zasco.

**Comment by NicoHaase** [comment] 2021-08-04 19:24
I think this is fixed now with #37

**Closed by NicoHaase** 2021-08-04 19:24 UTC
Labels: bug, help wanted
